### ISSUE TITLE
I get a feeling this will work better than a shared document

### ISSUE THREAD

**Issue by tleylan** [beefsweater/VRLX.Website#14]
The document is a good "overview" mechanism but we can see that tracking individual issues, actions, fixes and such doesn't work too well. The document will either continue to grow over time or stuff will have to be deleted meaning we lose the history. If this is system is available to us and tied directly to the project it seems like a better idea to me.

**Comment by beefsweater** [comment]
Ok, I've created an issue for the copyright. I'll now close this issue.

**Comment by tleylan** [comment]
Let's leave it open awhile until we get used to using this system.
