### ISSUE TITLE
Add Copyright

### ISSUE THREAD

**Issue by beefsweater** [beefsweater/VRLX.Website#23]
Add "© VR Language Exchange 2021" to copyright area on bottom of website

**Comment by tleylan** [comment]
Excellent. Jose can add a comment that he has done it and then he can close this issue.

**Comment by tleylan** [comment]
And you should be able to easily see why this works a lot better than a shared document. The initial request is incorrect which means it would have been implemented incorrectly the first time.

"© 2021 VR Language Exchange"
