### ISSUE TITLE
Higher resolution VRLX Logo (top banner) and Discord logo (bottom)

### ISSUE THREAD

**Issue by beefsweater** [beefsweater/VRLX.Website#44]
Here is the link to the VRLX logos: [https://drive.google.com/drive/folders/1D36L3MZ2bb8szABa8MZlcNb1yOShXvyq?usp=sharing](url)

The VRLX logo is a little fuzzy, I think from being resized multiple times.

The Discord logo seems to have been enlarged/stretched to fit. I'm sure we can find another one that is the perfect size. There should be a public PNG that we can download and resize/convert to jpg to use.

**Comment by tleylan** [comment]
these images have been updated
